#!/usr/bin/env python3
"""Generate docs/generated/feature-inventory.md from code introspection.

A dev script (not a ``gittan`` command): it enumerates gittan's user-facing
surface — CLI commands, collectors, and per-project config fields — straight from
the code so the inventory never drifts from reality.

Usage:
    python scripts/generate_feature_inventory.py          # (re)write the file
    python scripts/generate_feature_inventory.py --check   # fail if out of date

Output is deterministic (stable ordering, no timestamp) so ``--check`` can
regenerate-and-diff. The spec-linking / un-specced gate is a later phase.
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path
from typing import List, Tuple

REPO_ROOT = Path(__file__).resolve().parent.parent
# Run-from-anywhere: ensure the repo root is importable (sys.path[0] is scripts/
# when invoked as ``python scripts/generate_feature_inventory.py``).
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

OUTPUT_PATH = REPO_ROOT / "docs" / "generated" / "feature-inventory.md"
REGISTRY_PATH = REPO_ROOT / "core" / "collector_registry.py"
CONFIG_PATH = REPO_ROOT / "core" / "config.py"

BANNER = (
    "<!-- Generated by scripts/generate_feature_inventory.py — do not edit by "
    "hand. Run the script to refresh. -->"
)


def _first_line(text: str | None) -> str:
    for line in (text or "").strip().splitlines():
        stripped = line.strip()
        if stripped:
            return stripped
    return ""


def _command_name(info) -> str:
    """Typer keeps ``name=None`` when derived from the function name."""
    if getattr(info, "name", None):
        return str(info.name)
    callback = getattr(info, "callback", None)
    return (getattr(callback, "__name__", "") or "").replace("_", "-")


def discover_commands() -> List[Tuple[str, str, str]]:
    """Return ``(group, name, help)`` rows for every registered command.

    Importing ``core.cli`` registers all command modules on the shared Typer app
    as a side effect, so the app is the single source of truth.
    """
    from core.cli import app  # noqa: PLC0415 - import for its registration side effect

    rows: List[Tuple[str, str, str]] = []
    for info in app.registered_commands:
        rows.append(("", _command_name(info), _first_line(getattr(info.callback, "__doc__", ""))))
    for group in app.registered_groups:
        sub = group.typer_instance
        group_help = _first_line(getattr(sub.info, "help", "")) if getattr(sub, "info", None) else ""
        rows.append((group.name, "", group_help))
        for info in sub.registered_commands:
            rows.append((group.name, _command_name(info), _first_line(getattr(info.callback, "__doc__", ""))))
    rows.sort(key=lambda r: (r[0], r[1]))
    return rows


def _str_const(node: ast.AST | None) -> str | None:
    return node.value if isinstance(node, ast.Constant) and isinstance(node.value, str) else None


def discover_collectors() -> List[Tuple[str, str]]:
    """Return ``(name, unit_label)`` from the ``CollectorSpec(...)`` calls.

    Parsed via ``ast`` (not text/regex) so introspection needs no live args or
    collector callables and is robust to quoting/formatting style. ``CollectorSpec``
    is ``(name, collector, unit_label, ...)`` positionally, so we read args[0] and
    args[2].
    """
    tree = ast.parse(REGISTRY_PATH.read_text(encoding="utf-8"))
    rows: List[Tuple[str, str]] = []
    for node in ast.walk(tree):
        if (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Name)
            and node.func.id == "CollectorSpec"
            and len(node.args) >= 3
        ):
            name = _str_const(node.args[0])
            unit = _str_const(node.args[2])
            if name and unit:
                rows.append((name, unit))
    return sorted(set(rows))


def discover_config_fields() -> List[str]:
    """Return the per-project config field names read by ``normalize_profile``.

    Walks the function's AST for ``raw.get("field")`` calls — robust to quoting
    style, unlike a text scan.
    """
    tree = ast.parse(CONFIG_PATH.read_text(encoding="utf-8"))
    func = next(
        (n for n in ast.walk(tree) if isinstance(n, ast.FunctionDef) and n.name == "normalize_profile"),
        None,
    )
    if func is None:
        return []
    fields = set()
    for node in ast.walk(func):
        if (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Attribute)
            and node.func.attr == "get"
            and isinstance(node.func.value, ast.Name)
            and node.func.value.id == "raw"
            and node.args
        ):
            field = _str_const(node.args[0])
            if field:
                fields.add(field)
    return sorted(fields)


def render(commands, collectors, config_fields) -> str:
    lines: List[str] = [
        BANNER,
        "",
        "# Feature inventory (code-derived)",
        "",
        "Enumerated from the Typer app, the collector registry, and "
        "`normalize_profile`. The hand-written planning and specification docs "
        "live under `docs/`; spec linkage is a later phase.",
        "",
        "## Summary",
        "",
        "| Surface | Count |",
        "| --- | --- |",
        f"| Commands | {len([c for c in commands if c[1]])} |",
        f"| Command groups | {len([c for c in commands if not c[1]])} |",
        f"| Collectors | {len(collectors)} |",
        f"| Per-project config fields | {len(config_fields)} |",
        "",
        "## Commands",
        "",
        "| Group | Command | Help |",
        "| --- | --- | --- |",
    ]
    for group, name, help_text in commands:
        if not name:
            lines.append(f"| **{group}** | _(group)_ | {help_text} |")
        else:
            lines.append(f"| {group or '—'} | `{name}` | {help_text} |")
    lines += [
        "",
        "## Collectors",
        "",
        "| Source | Unit |",
        "| --- | --- |",
    ]
    lines += [f"| {name} | {unit} |" for name, unit in collectors]
    lines += [
        "",
        "## Per-project config fields",
        "",
        "Fields read by `core/config.py::normalize_profile`:",
        "",
    ]
    lines += [f"- `{field}`" for field in config_fields]
    lines.append("")
    return "\n".join(lines)


def build_inventory() -> str:
    return render(discover_commands(), discover_collectors(), discover_config_fields())


def main(argv: List[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the committed inventory is out of date (do not write).",
    )
    args = parser.parse_args(argv)
    content = build_inventory()

    if args.check:
        existing = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.is_file() else ""
        if existing != content:
            print(
                "feature-inventory.md is out of date. Run: "
                "python scripts/generate_feature_inventory.py",
                file=sys.stderr,
            )
            return 1
        print("feature-inventory.md is up to date.")
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
