#!/usr/bin/env python3
"""Generate docs/generated/feature-inventory.md from code introspection.

A dev script (not a ``gittan`` command): it enumerates gittan's user-facing
surface — CLI commands, collectors, and per-project config fields — straight from
the code so the inventory never drifts from reality.

Usage:
    python scripts/generate_feature_inventory.py          # (re)write the file
    python scripts/generate_feature_inventory.py --check   # fail if out of date

Output is deterministic (stable ordering, no timestamp) so ``--check`` can
regenerate-and-diff.

Traceability coupling (Phase 2, GH-230): each command/collector links to the
spec that covers it. A spec declares coverage explicitly with a ``covers:``
line in its ``## Traceability`` block (comma-separated command/collector
names — the robust key), or implicitly by a backtick mention
(`` `toggl-sync` `` / `` `gittan toggl-sync` ``) in the spec's **H1 title**
only — body/Traceability prose does not count, so a passing mention (or a
`related:` cross-reference) cannot claim coverage and suppress the
un-specced report. ``--check``
keeps the stale-file gate **hard**; the un-specced-feature report is
**advisory** by default and hard only with ``--strict`` (resolved gate
decision in docs/task-prompts/feature-inventory-generator-task.md).
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path
from typing import Dict, List, Tuple

REPO_ROOT = Path(__file__).resolve().parent.parent
# Run-from-anywhere: ensure the repo root is importable (sys.path[0] is scripts/
# when invoked as ``python scripts/generate_feature_inventory.py``).
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

OUTPUT_PATH = REPO_ROOT / "docs" / "generated" / "feature-inventory.md"
REGISTRY_PATH = REPO_ROOT / "core" / "collector_registry.py"
CONFIG_PATH = REPO_ROOT / "core" / "config.py"
SPEC_DIRS = ("docs/task-prompts", "docs/specs")

BANNER = (
    "<!-- Generated by scripts/generate_feature_inventory.py — do not edit by "
    "hand. Run the script to refresh. -->"
)


def _first_line(text: str | None) -> str:
    for line in (text or "").strip().splitlines():
        stripped = line.strip()
        if stripped:
            return stripped
    return ""


def _command_name(info) -> str:
    """Typer keeps ``name=None`` when derived from the function name."""
    if getattr(info, "name", None):
        return str(info.name)
    callback = getattr(info, "callback", None)
    return (getattr(callback, "__name__", "") or "").replace("_", "-")


def discover_commands() -> List[Tuple[str, str, str]]:
    """Return ``(group, name, help)`` rows for every registered command.

    Importing ``core.cli`` registers all command modules on the shared Typer app
    as a side effect, so the app is the single source of truth.
    """
    from core.cli import app  # noqa: PLC0415 - import for its registration side effect

    rows: List[Tuple[str, str, str]] = []
    for info in app.registered_commands:
        rows.append(("", _command_name(info), _first_line(getattr(info.callback, "__doc__", ""))))
    for group in app.registered_groups:
        sub = group.typer_instance
        group_help = _first_line(getattr(sub.info, "help", "")) if getattr(sub, "info", None) else ""
        rows.append((group.name, "", group_help))
        for info in sub.registered_commands:
            rows.append((group.name, _command_name(info), _first_line(getattr(info.callback, "__doc__", ""))))
    rows.sort(key=lambda r: (r[0], r[1]))
    return rows


def _str_const(node: ast.AST | None) -> str | None:
    return node.value if isinstance(node, ast.Constant) and isinstance(node.value, str) else None


def discover_collectors() -> List[Tuple[str, str]]:
    """Return ``(name, unit_label)`` from the ``CollectorSpec(...)`` calls.

    Parsed via ``ast`` (not text/regex) so introspection needs no live args or
    collector callables and is robust to quoting/formatting style. ``CollectorSpec``
    is ``(name, collector, unit_label, ...)`` positionally, so we read args[0] and
    args[2].
    """
    tree = ast.parse(REGISTRY_PATH.read_text(encoding="utf-8"))
    rows: List[Tuple[str, str]] = []
    for node in ast.walk(tree):
        if (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Name)
            and node.func.id == "CollectorSpec"
            and len(node.args) >= 3
        ):
            name = _str_const(node.args[0])
            unit = _str_const(node.args[2])
            if name and unit:
                rows.append((name, unit))
    return sorted(set(rows))


def discover_config_fields() -> List[str]:
    """Return the per-project config field names read by ``normalize_profile``.

    Walks the function's AST for ``raw.get("field")`` calls — robust to quoting
    style, unlike a text scan.
    """
    tree = ast.parse(CONFIG_PATH.read_text(encoding="utf-8"))
    func = next(
        (n for n in ast.walk(tree) if isinstance(n, ast.FunctionDef) and n.name == "normalize_profile"),
        None,
    )
    if func is None:
        return []
    fields = set()
    for node in ast.walk(func):
        if (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Attribute)
            and node.func.attr == "get"
            and isinstance(node.func.value, ast.Name)
            and node.func.value.id == "raw"
            and node.args
        ):
            field = _str_const(node.args[0])
            if field:
                fields.add(field)
    return sorted(fields)


_BACKTICK_RE = re.compile(r"`([^`\n]+)`")
_COVERS_RE = re.compile(r"^[-*\s]*covers:\s*(.+)$", re.IGNORECASE)
_STATUS_RE = re.compile(r"^[-*\s]*implementation_status:\s*(.+)$", re.IGNORECASE)


class SpecInfo:
    """Coverage facts parsed from one spec file."""

    def __init__(self, path: Path, covers: set[str], backticked: set[str], status: str):
        self.path = path
        self.covers = covers          # explicit `covers:` names (lowercased)
        self.backticked = backticked  # backticked tokens from the H1 title only
        self.status = status          # implementation_status value, may be ""

    def mentions(self, name: str) -> bool:
        if name.lower() in self.covers:
            return True
        return name in self.backticked or f"gittan {name}" in self.backticked


def _traceability_section(text: str) -> str:
    """Return the ``## Traceability`` section body (up to the next H2), or ""."""
    lines = text.splitlines()
    start = next(
        (i for i, ln in enumerate(lines) if ln.strip().lower().startswith("## traceability")),
        None,
    )
    if start is None:
        return ""
    end = next(
        (i for i in range(start + 1, len(lines)) if lines[i].startswith("## ")),
        len(lines),
    )
    return "\n".join(lines[start + 1 : end])


def _status_with_continuations(section_lines: List[str], idx: int, first: str) -> str:
    """Join a multi-line ``implementation_status:`` value (indented continuations)."""
    parts = [first]
    for line in section_lines[idx + 1 :]:
        # A continuation is indented and is not the next `- key:` bullet.
        if re.match(r"^\s{2,}\S", line) and not re.match(r"^\s*-\s", line):
            parts.append(line.strip())
        else:
            break
    return " ".join(parts)


def load_specs() -> List[SpecInfo]:
    """Parse every spec under SPEC_DIRS for coverage keys + implementation_status.

    ``covers:`` / ``implementation_status:`` are read **only** from the
    ``## Traceability`` section, and the backtick-mention fallback **only**
    from H1 title lines — body prose and Traceability cross-references
    (``related:``) cannot claim a feature (Qodo review on #395).
    """
    specs: List[SpecInfo] = []
    for rel in SPEC_DIRS:
        for path in sorted((REPO_ROOT / rel).rglob("*.md")):
            text = path.read_text(encoding="utf-8")
            section = _traceability_section(text)
            section_lines = section.splitlines()
            covers: set[str] = set()
            status = ""
            for i, line in enumerate(section_lines):
                covers_m = _COVERS_RE.match(line)
                if covers_m:
                    covers |= {t.strip().lower() for t in covers_m.group(1).split(",") if t.strip()}
                    continue
                status_m = _STATUS_RE.match(line)
                if status_m and not status:
                    status = _status_with_continuations(section_lines, i, status_m.group(1).strip())
            titles = "\n".join(ln for ln in text.splitlines() if ln.startswith("# "))
            specs.append(SpecInfo(path, covers, set(_BACKTICK_RE.findall(titles)), status))
    return specs


def link_feature_specs(names: List[str], specs: List[SpecInfo]) -> Dict[str, Tuple[str, str]]:
    """Map each feature name to ``(spec relative path, status)``; missing → absent.

    An explicit ``covers:`` match wins over a backtick mention; within each tier
    the first spec in path order is kept (deterministic).
    """
    linked: Dict[str, Tuple[str, str]] = {}
    for name in names:
        explicit = next((s for s in specs if name.lower() in s.covers), None)
        spec = explicit or next((s for s in specs if s.mentions(name)), None)
        if spec is not None:
            linked[name] = (spec.path.relative_to(REPO_ROOT).as_posix(), spec.status)
    return linked


def render(commands, collectors, config_fields, command_specs, collector_specs) -> str:
    lines: List[str] = [
        BANNER,
        "",
        "# Feature inventory (code-derived)",
        "",
        "Enumerated from the Typer app, the collector registry, and "
        "`normalize_profile`. Spec links come from `covers:` fields and "
        "backtick mentions in `docs/task-prompts/` + `docs/specs/` "
        "Traceability blocks; \"(no spec)\" rows are the un-specced surface "
        "reported by `--check` (advisory; hard with `--strict`).",
        "",
        "## Summary",
        "",
        "| Surface | Count |",
        "| --- | --- |",
        f"| Commands | {len([c for c in commands if c[1]])} |",
        f"| Command groups | {len([c for c in commands if not c[1]])} |",
        f"| Collectors | {len(collectors)} |",
        f"| Per-project config fields | {len(config_fields)} |",
        "",
        "## Commands",
        "",
        "| Group | Command | Help | Spec |",
        "| --- | --- | --- | --- |",
    ]
    for group, name, help_text in commands:
        if not name:
            lines.append(f"| **{group}** | _(group)_ | {help_text} | |")
        else:
            lines.append(
                f"| {group or '—'} | `{name}` | {help_text} | {_spec_cell(command_specs.get(name))} |"
            )
    lines += [
        "",
        "## Collectors",
        "",
        "| Source | Unit | Spec |",
        "| --- | --- | --- |",
    ]
    lines += [
        f"| {name} | {unit} | {_spec_cell(collector_specs.get(name))} |"
        for name, unit in collectors
    ]
    lines += [
        "",
        "## Per-project config fields",
        "",
        "Fields read by `core/config.py::normalize_profile`:",
        "",
    ]
    lines += [f"- `{field}`" for field in config_fields]
    lines.append("")
    return "\n".join(lines)


def _spec_cell(link: Tuple[str, str] | None) -> str:
    """Render one Spec table cell: relative link (+ status) or the no-spec flag."""
    if link is None:
        return "(no spec)"
    rel_path, status = link
    # The inventory lives in docs/generated/, so docs/... becomes ../...
    href = "../" + rel_path.removeprefix("docs/")
    label = rel_path.rsplit("/", 1)[-1].removesuffix(".md")
    cell = f"[{label}]({href})"
    if status:
        status = status if len(status) <= 60 else status[:57].rstrip() + "…"
        cell = f"{cell} · {status}"
    return cell


def build_feature_links() -> Tuple[Dict[str, Tuple[str, str]], Dict[str, Tuple[str, str]], List[str]]:
    """Return (command→spec, collector→spec, unspecced names) from the spec corpus."""
    commands = [name for _, name, _ in discover_commands() if name]
    collector_names = [name for name, _ in discover_collectors()]
    specs = load_specs()
    command_specs = link_feature_specs(commands, specs)
    collector_specs = link_feature_specs(collector_names, specs)
    unspecced = sorted(
        [f"command `{c}`" for c in commands if c not in command_specs]
        + [f"collector `{c}`" for c in collector_names if c not in collector_specs]
    )
    return command_specs, collector_specs, unspecced


def build_inventory() -> Tuple[str, List[str]]:
    command_specs, collector_specs, unspecced = build_feature_links()
    content = render(
        discover_commands(),
        discover_collectors(),
        discover_config_fields(),
        command_specs,
        collector_specs,
    )
    return content, unspecced


def main(argv: List[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the committed inventory is out of date (do not write).",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="With --check: also fail when a command/collector has no linked spec.",
    )
    args = parser.parse_args(argv)
    content, unspecced = build_inventory()

    if args.check:
        failed = False
        existing = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.is_file() else ""
        if existing != content:
            print(
                "feature-inventory.md is out of date. Run: "
                "python scripts/generate_feature_inventory.py",
                file=sys.stderr,
            )
            failed = True
        if unspecced:
            # Advisory by default (resolved gate decision); hard with --strict.
            severity = "ERROR" if args.strict else "WARNING"
            print(f"{severity}: {len(unspecced)} feature(s) with no linked spec:", file=sys.stderr)
            for item in unspecced:
                print(f"  - {item}", file=sys.stderr)
            if args.strict:
                failed = True
        if failed:
            return 1
        print("feature-inventory.md is up to date.")
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    if unspecced:
        print(f"note: {len(unspecced)} feature(s) with no linked spec (see --check)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
