#!/usr/bin/env python3
"""Generate docs/generated/release-ledger.md — what shipped in which version.

A dev script (not a ``gittan`` command). It answers "what came in 0.5.0?" from
data rather than from a hand-maintained table, because the hand-maintained one
(``docs/specs/implementation-status.md``) went two months stale and disagreed
with the repo in several rows.

Three local sources, no network:

1. ``CHANGELOG.md`` version headings (``## X.Y.Z - YYYY-MM-DD``).
2. Git tags ``vX.Y.Z`` — which of those versions were actually cut.
3. Merge-commit subjects in each tag range, which carry ``(#N)`` because the
   repo squash-merges. That is the only signal with full coverage, so it is the
   spine of every range.

Spec links come from the two weaker signals, and the report says so: ``GH-``
ids cited in a release's own changelog section, and ``implementation.pr`` /
``story_id`` in a spec's ``## Traceability`` block. A pull request nothing
claims is listed rather than hidden — the same advisory shape as
``generate_feature_inventory.py``'s un-specced report.

Usage:
    python scripts/generate_release_ledger.py           # (re)write the file
    python scripts/generate_release_ledger.py --check   # fail if out of date

``--check`` is a no-op (exit 0 with a note) when git cannot answer — a shallow
clone or a checkout without tags, which is what ``actions/checkout`` produces by
default. Wiring this into CI needs ``fetch-depth: 0`` first.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, NamedTuple, Optional, Set

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPTS_DIR = REPO_ROOT / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

# One parser for the Traceability block, shared with the feature inventory so
# the two generators cannot disagree about what a block says.
from generate_feature_inventory import _traceability_section  # noqa: E402

OUTPUT_PATH = REPO_ROOT / "docs" / "generated" / "release-ledger.md"
CHANGELOG_PATH = REPO_ROOT / "CHANGELOG.md"
SPEC_DIRS = ("docs/task-prompts", "docs/specs")

BANNER = (
    "<!-- Generated by scripts/generate_release_ledger.py — do not edit by "
    "hand. Run the script to refresh. -->"
)

_RELEASE_HEADING_RE = re.compile(r"^(\d+\.\d+\.\d+)\s+-\s+(\d{4}-\d{2}-\d{2})\s*$")
_STORY_RE = re.compile(r"\b(?:GH|JIRA)-(\d+)\b")
_PR_SUBJECT_RE = re.compile(r"\(#(\d+)\)")
_STATUS_RE = re.compile(r"^[-*\s]*implementation_status:\s*(.+)$", re.IGNORECASE)
_STORY_ID_RE = re.compile(r"^[-*\s]*story_id:\s*(.+)$", re.IGNORECASE)
_IMPL_PR_RE = re.compile(r"^[-*\s]*implementation\.pr:\s*(.+)$", re.IGNORECASE)


class Release(NamedTuple):
    version: str
    date: str
    story_ids: Set[str]  # bare numbers cited in the section body


class Commit(NamedTuple):
    sha: str
    subject: str
    pr: Optional[str]


class SpecRef(NamedTuple):
    path: str
    status: str
    story_ids: Set[str]
    prs: Set[str]


def _git(*args: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(REPO_ROOT), *args],
        capture_output=True,
        text=True,
        check=False,
    )
    return result.stdout.strip() if result.returncode == 0 else ""


def project_version() -> str:
    """``[project] version`` from pyproject.toml, or ``""``."""
    text = (REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8")
    match = re.search(r'^version\s*=\s*"([^"]+)"', text, re.M)
    return match.group(1) if match else ""


def git_can_answer() -> bool:
    """False when git cannot produce a report a full clone would reproduce.

    A shallow clone resolves recent ranges and silently reports ``0 commits``
    for older ones, which would write a file that disagrees with every normal
    checkout and make ``--check`` fail for the next person. Refusing is the
    honest answer; ``git fetch --unshallow`` is the fix.
    """
    if _git("rev-parse", "--is-shallow-repository") == "true":
        return False
    return bool(_git("tag", "--list", "v*.*.*"))


def open_end_ref() -> str:
    """Ref that ends the current, still-unreleased line.

    Not ``HEAD``: this file is committed, and ``HEAD`` makes its contents depend
    on which branch you generated from, so every feature branch would fail
    ``--check``. The default branch is the same everywhere.
    """
    for ref in ("origin/main", "main"):
        if _git("rev-parse", "--verify", "--quiet", f"{ref}^{{commit}}"):
            return ref
    return "HEAD"


def changelog_releases() -> List[Release]:
    """Dated release sections, newest first, with the story ids each cites."""
    text = CHANGELOG_PATH.read_text(encoding="utf-8")
    sections = re.split(r"^## ", text, flags=re.M)[1:]
    releases: List[Release] = []
    for section in sections:
        lines = section.splitlines()
        match = _RELEASE_HEADING_RE.match(lines[0].strip())
        if not match:
            continue  # "Unreleased" and any draft heading
        body = "\n".join(lines[1:])
        releases.append(
            Release(match.group(1), match.group(2), set(_STORY_RE.findall(body)))
        )
    return releases


_SEMVER_TAG_RE = re.compile(r"^v(\d+\.\d+\.\d+)$")


def release_tags() -> tuple[Dict[str, str], List[str]]:
    """``({version: tag}, [off-format tags])``.

    Only strict ``vX.Y.Z`` counts as a release tag. A pre-release or hand-named
    tag (``v0.2.5rc1-something``) is reported separately rather than parsed as a
    version, because the PyPI workflow keys on the strict form.
    """
    tags: Dict[str, str] = {}
    other: List[str] = []
    for line in _git("tag", "--list", "v*").splitlines():
        tag = line.strip()
        if not tag:
            continue
        match = _SEMVER_TAG_RE.match(tag)
        if match:
            tags[match.group(1)] = tag
        else:
            other.append(tag)
    return tags, sorted(other)


def commits_between(start: Optional[str], end: str) -> List[Commit]:
    rev = f"{start}..{end}" if start else end
    raw = _git("log", "--no-merges", "--format=%h%x1f%s", rev)
    commits = []
    for line in raw.splitlines():
        if "\x1f" not in line:
            continue
        sha, subject = line.split("\x1f", 1)
        found = _PR_SUBJECT_RE.findall(subject)
        commits.append(Commit(sha, subject, found[-1] if found else None))
    return commits


def load_spec_refs() -> List[SpecRef]:
    """Traceability facts per spec: status, story ids, and referenced PRs."""
    refs: List[SpecRef] = []
    for rel in SPEC_DIRS:
        for path in sorted((REPO_ROOT / rel).rglob("*.md")):
            section = _traceability_section(path.read_text(encoding="utf-8"))
            if not section:
                continue
            status, stories, prs = "", set(), set()
            for line in section.splitlines():
                status_m = _STATUS_RE.match(line)
                if status_m:
                    status = status_m.group(1).strip().strip("`")
                story_m = _STORY_ID_RE.match(line)
                if story_m:
                    stories |= set(_STORY_RE.findall(story_m.group(1)))
                pr_m = _IMPL_PR_RE.match(line)
                if pr_m:
                    prs |= set(re.findall(r"#?(\d+)", pr_m.group(1)))
            refs.append(
                SpecRef(str(path.relative_to(REPO_ROOT)), status, stories, prs)
            )
    return refs


def specs_for_release(
    release: Release, prs: Set[str], refs: List[SpecRef]
) -> List[SpecRef]:
    """Specs this release can be shown to have delivered.

    Two independent claims, both weak on their own, so both are accepted: a
    story id the release's changelog section cites, or a pull request in the
    range that the spec names in ``implementation.pr``.
    """
    matched = [
        ref
        for ref in refs
        if (ref.story_ids & release.story_ids) or (ref.prs & prs)
    ]
    return sorted(matched, key=lambda r: r.path)


def _range_for(
    release: Release, index: int, releases: List[Release], tags: Dict[str, str]
) -> tuple[Optional[str], str, bool]:
    """``(start_ref, end_ref, tagged)`` for one release's commit range.

    A tagged release is exact: previous tag to its own tag.

    An untagged one has no end point of its own, so it is bounded by the
    nearest *newer* tag — not by the branch tip, which would hand a 2026-05
    release every commit since. When no newer tag exists the release is the
    current line and the range runs to the default branch.

    Consecutive untagged releases therefore share one range, because nothing in
    git separates them. The report says so rather than printing the same
    numbers three times as if each had been measured.
    """
    tag = tags.get(release.version)
    if tag:
        end = tag
    else:
        end = open_end_ref()
        for newer in reversed(releases[:index]):
            if newer.version in tags:
                end = tags[newer.version]
                break
    start = None
    for older in releases[index + 1 :]:
        if older.version in tags:
            start = tags[older.version]
            break
    return start, end, bool(tag)


def build_report() -> str:
    releases = changelog_releases()
    tags, off_format_tags = release_tags()
    refs = load_spec_refs()
    newest_tagged = next(
        (r.version for r in releases if r.version in tags), None
    )

    rows: List[str] = []
    sections: List[str] = []
    untagged: List[str] = []
    orphan_tags = sorted(set(tags) - {r.version for r in releases})

    for index, release in enumerate(releases):
        start, end, tagged = _range_for(release, index, releases, tags)
        commits = commits_between(start, end)
        prs = {c.pr for c in commits if c.pr}
        specs = specs_for_release(release, prs, refs)
        if not tagged:
            untagged.append(release.version)

        rows.append(
            f"| `{release.version}` | {release.date} | "
            f"{'`v' + release.version + '`' if tagged else '**none**'} | "
            f"{len(commits)} | {len(prs)} | {len(specs)} |"
        )

        head = f"### {release.version} — {release.date}"
        if not tagged:
            head += "  ⚠ not tagged"
        body = [head, ""]
        if not tagged:
            shared = [
                other.version
                for j, other in enumerate(releases)
                if j != index
                and other.version not in tags
                and _range_for(other, j, releases, tags)[:2] == (start, end)
            ]
            note = (
                "> No `v%s` tag exists, so nothing was published for this "
                "version." % release.version
            )
            if end not in tags.values():
                note += (
                    " The range below runs to `%s` and may include commits "
                    "merged after the release notes were written." % end
                )
            else:
                note += (
                    " It is bounded by the surrounding tags, so its commits are "
                    "also counted under `%s` — no tag separates them."
                    % end.lstrip("v")
                )
            if shared:
                note += (
                    " The same range covers %s."
                    % ", ".join(f"`{v}`" for v in sorted(shared))
                )
            body.append(note)
            body.append("")
        body.append(
            f"Range: `{start or 'root'}..{end}` — {len(commits)} commit(s), "
            f"{len(prs)} pull request(s)."
        )
        body.append("")
        if specs:
            body.append("| Spec | Status |")
            body.append("| --- | --- |")
            for spec in specs:
                body.append(f"| `{spec.path}` | {spec.status or '—'} |")
        else:
            body.append("No spec claims this release.")
        body.append("")

        unlinked = sorted(
            (c for c in commits if c.pr and not _claimed(c.pr, specs)),
            key=lambda c: int(c.pr or 0),
        )
        if unlinked:
            body.append(
                f"<details><summary>{len(unlinked)} pull request(s) no spec "
                "claims</summary>"
            )
            body.append("")
            for commit in unlinked:
                body.append(f"- #{commit.pr} — {commit.subject}")
            body.append("")
            body.append("</details>")
            body.append("")
        sections.append("\n".join(body))

    out = [
        BANNER,
        "",
        "# Release ledger (code-derived)",
        "",
        "What shipped in which version, derived from `CHANGELOG.md` headings, "
        "git tags, and the `(#N)` pull request in each squash-merged commit "
        "subject. Spec links come from `GH-` ids cited in a release's own "
        "changelog section and from `implementation.pr` in a spec's "
        "`## Traceability` block, so they are partial by construction — the "
        "pull requests no spec claims are listed per release rather than "
        "dropped.",
        "",
        "## Summary",
        "",
        "| Version | Date | Tag | Commits | PRs | Specs |",
        "| --- | --- | --- | --- | --- | --- |",
        *rows,
        "",
    ]
    # Only an untagged version *newer* than the newest tag is still fixable.
    # An untagged 2026-04 version is history: it is in the table, and nobody is
    # going back to cut it. Listing all ten buries the one that matters.
    versions = [r.version for r in releases]
    cutoff = versions.index(newest_tagged) if newest_tagged in versions else len(versions)
    actionable = [v for v in untagged if versions.index(v) < cutoff]
    historical = [v for v in untagged if versions.index(v) >= cutoff]
    declared = project_version()

    notes: List[str] = []
    for version in actionable:
        line = (
            f"- **`{version}` is written but never released.** `CHANGELOG.md` "
            f"has a dated section"
        )
        if declared == version:
            line += f" and `pyproject.toml` declares `{version}`"
        line += (
            f", but no `v{version}` tag exists. `.github/workflows/pypi.yml` "
            f"publishes on tag push, so PyPI never received it."
        )
        notes.append(line)
    if historical:
        notes.append(
            "- %d older version(s) were never tagged either (%s). Historical — "
            "listed in the table above, not worth cutting now."
            % (len(historical), ", ".join(f"`{v}`" for v in historical))
        )
    for tag in orphan_tags:
        notes.append(
            f"- **Tag `v{tag}` has no dated `CHANGELOG.md` section.** The GitHub "
            f"Release job builds its body from that section, so the release page "
            f"for this tag is empty or missing."
        )
    if off_format_tags:
        notes.append(
            "- %d tag(s) do not match `vX.Y.Z` and are ignored here (%s). The "
            "PyPI workflow keys on the strict form, so these never published."
            % (len(off_format_tags), ", ".join(f"`{t}`" for t in off_format_tags))
        )
    if notes:
        out += ["## Needs attention", "", *notes, ""]
    out += ["## Releases", ""] + sections
    return "\n".join(out).rstrip() + "\n"


def _claimed(pr: str, specs: List[SpecRef]) -> bool:
    return any(pr in spec.prs for spec in specs)


def main(argv: List[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when the committed file differs from a fresh run.",
    )
    args = parser.parse_args(argv)

    if not git_can_answer():
        print(
            "release-ledger: shallow clone or no release tags; skipping "
            "(CI needs fetch-depth: 0 and tags to run this)."
        )
        return 0

    content = build_report()
    if args.check:
        existing = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.is_file() else ""
        if existing != content:
            print(
                f"{OUTPUT_PATH.relative_to(REPO_ROOT)} is out of date — run "
                "python scripts/generate_release_ledger.py",
                file=sys.stderr,
            )
            return 1
        print(f"{OUTPUT_PATH.relative_to(REPO_ROOT)} is up to date")
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
